spring:
  application:
    name: "dripify"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/dripify_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${dbName}
    password: ${dbPassword}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#      show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

cloudinary:
  link: cloudinary://857539398347255:fCTKByWpLAfDvil6ICUgaaiy50Q@dpj028iin