package com.dripify.order.model;

public enum City {
    SOFIA, PLOVDIV, VARNA, BURGAS, RUSE, STARA_ZAGORA("STARA ZAGORA"),
    PLEVEN, SLIVEN, DOBRICH, SHUMEN, PERNIK, YAMBOL,
    HASKOVO, PAZARDZHIK, BLAGOEVGRAD, VELIKO_TARNOVO("VELIKO TARNOVO"),
    VRATSA, GABROVO, VIDIN, ASENOVGRAD, KYUSTENDIL,
    KARDJALI, KAZANLAK, MONTANA, DIMITROVGRAD, LOVECH,
    TARGOVISHTE, SILISTRA, DUPNITSA, RAZGRAD, GORNA_ORYAHOVITSA("GORNA ORYAHOVITSA"),
    SVISHTOV, SMOLYAN, PETRICH, SANDANSKI, SAMOKOV, SEVLIEVO,
    KARLOVO, NOVA_ZAGORA("NOVA ZAGORA"), VELINGRAD, TROJAN, AYTOS, BOTEVGRAD,
    GOTSE_DELCHEV("GOTSE DELCHEV"), PESHTERA, HARMANLI, POMORIE, BALCHIK, KAVARNA,
    NESSEBAR, TRYAVNA, BANKYA, TUTRAKAN, VELIKI_PRESLAV("VELIKI PRESLAV"), BANSKO,
    HISARYA, VARSHETS, TSAREVO, BELOGRADCHIK, SOZOPOL, ARDINO,
    SHABLA, BATAK, PRIMORSKO, APRILTSI, SVETI_VLAS("SVETI VLAS"), KOPRIVSHTITSA,
    BYALA, ALFATAR, ANTONOVO, SHIPKA, AHTOPOL, PLISKA, KITEN, MELNIK;

    private final String name;

    City(String name) {
        this.name = name;
    }

    City() {
        this.name = name();
    }

    @Override
    public String toString() {
        if (name != null) {
            return name;
        }

        return name();
    }
}
